version: "3"
tasks:
  workflow-conditional:
    desc: "Runs the MAF workflow with conditional steps"
    cmds:
      - uv run python -m samples.workflow_conditional {{.CLI_ARGS}}

  multi-turns-conversation:
    desc: "Runs the MAF multi-turns-conversation sample"
    cmds:
      - uv run python -m samples.multi_turns_conversation

  custom-context-providers:
    desc: "Runs the MAF custom-context-providers sample"
    cmds:
      - uv run python -m samples.custom_context_providers

  concurrent-agent-calls:
    desc: "Runs the MAF concurrent_agent_calls sample"
    cmds:
      - uv run python -m samples.concurrent_agent_calls

  fan-in-fan-out:
    desc: "Runs the MAF fan-in-fan-out sample"
    cmds:
      - uv run python -m samples.fan_in_fan_out

  test-unit:
    desc: "Runs unit tests with pytest"
    cmds:
      - uv run python -m pytest -p no:warnings --cov-report term-missing
        --cov=maf_workflow tests

  util-format-code:
    desc: "Formats the code using ruff"
    cmds:
      - uv run ruff format .

  util-lint:
    desc: "Runs linting with Ruff"
    cmds:
      - uv run ruff check .
      - uv run pyright .

  util-gen-requirements-txt:
    desc: "Generates requirements.txt from the current environment"
    cmds:
      - uv lock
      - uv export --frozen --no-dev --output-file=requirements.txt
      - uv export --frozen --all-groups --output-file=requirements.dev.txt

  util-pip-audit:
    desc: "Runs pip-audit to check for vulnerabilities"
    cmds:
      - uv run pip-audit -r requirements.txt
      - uv run pip-audit -r requirements.dev.txt
